name: svcntrl
version: '1.1.21'
main: com.svcntrl.paper.SvcntrlPlugin
api-version: '1.21'
author: florentem
description: Server-side version control for Minecraft builds
permissions:
  svcntrl.admin:
    description: Full administrative access to all svcntrl projects
    default: op
  svcntrl.command.save:
    default: true
  svcntrl.command.restore:
    default: true
  svcntrl.command.project.create:
    default: true
  svcntrl.command.project.list:
    default: true
  svcntrl.command.project.select:
    default: true
  svcntrl.command.project.tp:
    default: true
  svcntrl.command.project.raycast:
    default: true
  svcntrl.command.project.remove:
    default: true
  svcntrl.command.project.trust:
    default: true
  svcntrl.command.project.untrust:
    default: true
  svcntrl.command.branch.create:
    default: true
  svcntrl.command.branch.checkout:
    default: true
  svcntrl.command.branch.list:
    default: true
  svcntrl.command.branch.delete:
    default: true
  svcntrl.command.log:
    default: true
  svcntrl.command.outline:
    default: true
  svcntrl.command.preview:
    default: true
  svcntrl.command.export:
    default: true
  svcntrl.command.reload:
    default: op
